### PR TITLE
fix ConformingDelaunayTriangulationBuilder

### PR DESCRIPTION
**Pull request by gaomeng1900**
Errors thrown when using ConformingDelaunayTriangulationBuilder. Fixed by adding these 2 methods.

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Looks nice, thanks.

**Comment by harrixon** [comment]
The 2 fixes in this MR does not exist in current version (2.9.3), were they supposed to be removed?
This is breaking `ConformingDelaunayTriangulationBuilder`.

**Comment by bjornharrtell** [comment]
@harrixon no looks like I unintentionally removed them in https://github.com/bjornharrtell/jsts/commit/b5615f3e2513b6b671f0f4396aaaccb3a4b9d933. It's unfortunate no tests was added for this case which would have caught the regression.

**Comment by bjornharrtell** [comment]
I have opened https://github.com/bjornharrtell/jsts/issues/490 to track the regression.

**Pull request merged**
