### PR TITLE
Add linearref to dist

### PR DESCRIPTION
**Pull request by Alfaspider**
Linearref was missing in generated dist file. I've added it.

### CODE REVIEW

**Comment by bjornharrtell** [comment]
LGTM but I'd like to have JSTS mirror upstream copyright/license status which requires any contributors to sign https://eclipse.org/legal/CLA.php. Please report back if you can sign that CLA or not.

**Comment by Alfaspider** [comment]
Shure, where and what do I need to sign?

**Comment by bjornharrtell** [comment]
It seems the correct link to signup is probably https://eclipse.org/contribute/cla. Let me know if it works.

**Comment by Alfaspider** [comment]
Hi, agreement signed. Is this all or do you need anything else?

**Comment by bjornharrtell** [comment]
That's all, thanks for the contribution!

**Pull request merged**
