### PR TITLE
Fix ES5 compatibility issue

### PR DESCRIPTION
**Pull request by allknower**
#341

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Oh, thanks, but I did it myself just now. :)

**Comment by bjornharrtell** [comment]
Hmm but I see you suggest `Math.log(x) / Math.LN2` while I did `Math.log(x) * Math.LOG2E`. What is correct?

**Comment by bjornharrtell** [comment]
Answer is both.

**Comment by allknower** [comment]
Thanks a lot.

**Pull request closed without merging**
