### PR TITLE
Removed copy of non existent index.js

### PR DESCRIPTION
**Pull request by DataCamper**

### CODE REVIEW

**Comment by doug-numetric** [comment]
[package.js](https://github.com/bjornharrtell/jsts/blob/master/package.json#L37) is also referencing this empty file.

I have noticed that this causes an issue with webpack bundle builds -- (see https://github.com/webpack/webpack/issues/5673) -- webpack prioritizes module over main to resolve
```javascript
const jsts = require('jsts')
```
So the require is returning an empty object because the `index.js` file is empty. And the common convention is to turn off babel for `node_modules` so to work around the issue, you have to whitelist `node_modules/jsts` in the `babel-loader` and use something like 
```javascript
import * as jsts from 'jsts'
```

**Comment by bjornharrtell** [comment]
Thanks for the input @doug-numetric.

I find it quite hard to see what the "right" change is here, but will attempt to consider it for the next release.

**Comment by doug-numetric** [comment]
@bjornharrtell While trying to debug the issue on my end, I came across the following possible fix.

https://github.com/bjornharrtell/jsts/pull/348

It's just an idea... I haven't tested it out yet so... grain of salt...

**Comment by bjornharrtell** [comment]
Investigating this to be able to make a new release and I'm still unsure. The reason for the empty index.js is to indicate that ES6 modules are available but there is no entry point module. A more involved explanation was given in https://github.com/bjornharrtell/jsts/issues/311.

**Comment by bjornharrtell** [comment]
I've just made a 1.6.2 release without an empty index.js module. Not sure if it will help or if it will cause other issues and would appreciate any feedback from testing it with webpack and elsewhere.

**Comment by bjornharrtell** [comment]
This is now obsolete.

**Pull request closed without merging**
