### PR TITLE
Add util packages to single file build

### LINKED ISSUE #379: jsts object is missing utils package
The util package is not included in the jsts object. There are some useful classes, such as the org.locationtech.jts.util.GeometricShapeFactory. I'm not sure if this was done intentionally or just missed. 

For a node project, the workaround is to import the file directly: 
```
import GeomerticShapeFactory from 'jsts/src/org/locationtech/jts/util/'
var factory = new GeomerticShapeFactory ();
```

### PR DESCRIPTION
**Pull request by wallw-bits**
This adds the util packages `src/org/locationtech/jts/util` and `src/org/locationtech/jts/geom/util` to the single file build.

resolves #379

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Looks good but I would like to avoid adding internal stuff to the full build, like fx. Assert. Could you trim down the exports to the useful classes?

**Comment by wallw-bits** [comment]
I do not think I know enough about the other classes in there to make a distinction on whether or not they would be useful. However, the most recent commit takes a crack at it.

**Comment by bjornharrtell** [comment]
Looks good to me, merging. Thanks for the contribution. :)

**Comment by wallw-bits** [comment]
Is there a timeline for a release with this addition? If not, then we can certainly package our own build of it, but we prefer to use the npm releases where possible.

Thanks!

**Comment by bjornharrtell** [comment]
No.

**Pull request merged**
