### PR TITLE
Improve ES6 modules support

### PR DESCRIPTION
**Pull request by DenisCarriere**
# Improve ES6 modules support

Fixes: https://github.com/bjornharrtell/jsts/issues/311
Ref: https://github.com/bjornharrtell/jsts/issues/252 https://github.com/Turfjs/turf/pull/960

@bjornharrtell There's a significant amounts of changes, so I've divided the commits into 3 parts:

- [Refactor ES6 modules](https://github.com/bjornharrtell/jsts/commit/1eca4c865d5379f75faaae0d72f6e0cf530af030)
- [Modify Rollup configuration](https://github.com/bjornharrtell/jsts/commit/3b832e54aaed4e365d9a47066ae68af17d099b0a)
- [Change mocha tests to ES5+ (NodeJS 6 compatible)](https://github.com/bjornharrtell/jsts/commit/82b73682900e154543353b55a6ea61fe2a6ca8c4)

Running the `jsts` tests now run really fast! Takes only 5s to complete the entire `npm test` process.

```bash
$ time npm test
npm test  5.86s user 0.52s system 110% cpu 5.760 total
```

## ES6 Modules exposed at `module`

Now you can access directly methods/Classes directly from the main repo, when doing this with Rollup or other bundlers that support ES6 modules the Tree Shaking "should" now happen and make the bundle size significantly smaller.

```js
import { WKTReader, GeoJSONReader } from 'jsts'
```
Only downfall to importing specific modules like this is you might not have all features which get extended by other modules, the user might need to import more modules to get the desired outcome. If the CommonJS bundle is imported then there's no issue.

## Bundle sizes

There hasn't been a reduction of size (496KB minified), however if a 3rd party library only imports specific modules then that bundle size would be significantly smaller.

```
848K    dist/jsts.js
2.0M    dist/jsts.js.map
496K    dist/jsts.min.js
1.5M    dist/jsts.min.js.map
840K    dist/jsts.mjs
2.0M    dist/jsts.mjs.map
```

## Main files

There's 3 main files:
- Minified for the web (`index.min.js`) which is Uglified + UMD format + ES5 (Babel)
- CommonJS (`dist/index.js`) ES6 source code (except ES6 export/modules)
- ES Modules (`dist/index.mjs`) ES6 source code

```json
  "main": "dist/jsts.js",
  "module": "dist/jsts.mjs",
  "jsnext:main": "dist/jsts.mjs",
```

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Why flatten namespaces? To me that seems like a deviation from upstream which I don't like and benefits are not clear to me.

For my rationale on the current design see https://github.com/bjornharrtell/jsts/issues/311.

In short I don't yet understand what the problem is, if there is one. I'm successfully depending on JSTS myself in several projects using Rollup and importing individual ES6 modules directly. The file `jsts.js` and similar ones for sub-namespaces are *only* intended and used for the ES5 bundle so I'm not sure why they are even involved if you want to use the ES6 modules directly.

**Comment by DenisCarriere** [comment]
@bjornharrtell I agreed with you, flattening the namespace actually ruined the whole purpose of using Rollup (making the bundle size smaller).

The issue was the monkey patching, so many modules depend on each other and it's impossible to figure out which module needs what by importing single modules.

I'm not familiar enough with the code base to decrypt the methods and know how to use it with the ES modules.

@bjornharrtell Do you have basic examples of how to use it, at least the basic ones described in your documentation.

## For example - How to apply buffer?

**CommonJS**

```
var jsts = require('jsts')
var reader = new jsts.io.WKTReader()
var a = reader.read('POINT (-20 0)')
var b = reader.read('POINT (20 0)')
a = a.buffer(40)
b = b.buffer(40)
```

**ES6** (Broken) - Most logical one

```js
import WKTReader from 'jsts/io/WKTReader'
var a = reader.read('POINT (-20 0)')
var b = reader.read('POINT (20 0)')
a = a.buffer(40)
b = b.buffer(40)
```

```
Error [ERR_MISSING_MODULE]: Cannot find module jsts/io/WKTReader
    at Object.<anonymous> (/Users/mac/Github/turf/packages/turf-buffer/main.js:5:28)
    at Object.<anonymous> (/Users/mac/Github/turf/packages/turf-buffer/main.js)
npm ERR! Test failed.  See above for more details.
```

**ES6** (Broken) - No one would of guessed this filepath

```js
import WKTReader from 'jsts/org/locationtech/jsts/io/WKTReader';
```

```
Error [ERR_MISSING_MODULE]: Cannot find module jsts/org/locationtech/jsts/io/WKTReader
    at Object.<anonymous> (/Users/mac/Github/turf/packages/turf-buffer/main.js:5:28)
    at Object.<anonymous> (/Users/mac/Github/turf/packages/turf-buffer/main.js)
npm ERR! Test failed.  See above for more details.
```

I'm not even at the Buffer operation, I'm sure that will also break...

**Comment by DenisCarriere** [comment]
Had to use `jsts/org/org` since `src` isn't being published in the most recent npm build.

```
import jsts from 'jsts/org/org/locationtech/jts/io/WKTReader';
```

**Comment by bjornharrtell** [comment]
`jsts/org/org/locationtech/jts/io/WKTReader` looks wrong, it's intended to be be `jsts/org/locationtech/jts/io/WKTReader`. I'll look into that.

**Comment by DenisCarriere** [comment]
I'll try that one, I think they both "work" but don't know why they are both published on npm if only one is meant to be used.

https://unpkg.com/jsts@1.4.0/org/

**Comment by bjornharrtell** [comment]
I think I've just made a mistake in the publish.

**Comment by DenisCarriere** [comment]
Oh, doesn't seem like the published npm version syncs up with your current `1.4.0` repo. That might help a lot 👍

**Comment by DenisCarriere** [comment]
Let me attempt to make a simplistic repo of your `jsts` buffer example. I'll post the URL here

**Comment by bjornharrtell** [comment]
I managed to completely rewrite my example page with direct module usage via unpkg. Of course only works in browsers that support module loading directly. Trying it out in Chrome 61 seems to work like a charm.

See http://bjornharrtell.github.io/jsts/index_modules.html.

**Comment by DenisCarriere** [comment]
👍 Looking forward to work with ES modules natively in the browser, new world! 😄

**Pull request closed without merging**
