### PR TITLE
Implement a better polyfill for Array#fill

### PR DESCRIPTION
**Pull request by tchandelle**
The current polyfill pollute the Array prototype, fill method is
listable with for in loop.

### CODE REVIEW

**Comment by bjornharrtell** [comment]
LGTM but I'd like to have JSTS mirror upstream copyright/license status which requires any contributors to sign https://eclipse.org/legal/CLA.php. Please report back if you can sign that CLA or not.

**Comment by tchandelle** [comment]
@bjornharrtell : What if the code is not from me, do I still need to sign the CLA? As you can see, I just copy-pasted the polyfill from [polyfill.io](https://polyfill.io), which is under MIT license.

**Comment by bjornharrtell** [comment]
Good point, I agree it's not needed for this PR but you also have #290. :)

**Comment by tchandelle** [comment]
Yes, of course. I'll have to check with my employer, but it should be ok.

**Comment by bjornharrtell** [comment]
Manually replaced existing polyfill.

**Pull request closed without merging**
